// src/lib/print.js

export function printQuote(order, admin) {
  const q = order.quote;
  const org = admin.orgName || "Brand M3dia";
  const brand = "#dc2626"; // Tailwind red-600 default
  const logo = "/brand-logo.png"; // place your logo in /public

  const itemsRows = (q?.lineItems || [])
    .map(
      (li) => `
      <tr>
        <td>${esc(li.label)}</td>
        <td style="text-align:right">${fmt(li.amount, q.currency)}</td>
        <td style="text-align:right">${li.qty}</td>
        <td style="text-align:right">${fmt(li.total, q.currency)}</td>
      </tr>`
    )
    .join("");

  const notes = (q?.notes || []).map((n) => `<li>${esc(n)}</li>`).join("");

  const html = `<!doctype html>
<html>
<head>
<meta charset="utf-8" />
<title>Quote – ${esc(order.orderId)}</title>
<style>
  :root { --brand: ${brand}; }
  body { font-family: system-ui, -apple-system, Segoe UI, Roboto, Ubuntu, Helvetica, Arial, sans-serif; padding:24px; }
  .header { display:flex; align-items:center; gap:12px; }
  .logo { height:36px; }
  .brand { color: var(--brand); font-weight: 700; }
  .rule { height:3px; background: var(--brand); margin:12px 0 16px 0; }
  table { width: 100%; border-collapse: collapse; }
  th, td { border-bottom: 1px solid #e5e7eb; padding: 8px; font-size: 14px; }
  th { text-align: left; background: #f8fafc; }
  .totals { margin-top: 12px; width: 320px; margin-left: auto; }
  .totals td { padding: 6px 8px; }
  .right { text-align: right; }
  .muted { color: #6b7280; font-size: 12px; }
</style>
</head>
<body>
  <div class="header">
    <img class="logo" src="${logo}" alt="${esc(org)}" />
    <div>
      <div class="brand">${esc(org)}</div>
      <div>Quotation</div>
    </div>
    <div style="margin-left:auto; text-align:right">
      <div><strong>Order ID:</strong> ${esc(order.orderId)}</div>
      ${order.client?.clientName ? `<div><strong>Client:</strong> ${esc(order.client.clientName)}</div>` : ""}
      <div><strong>Date:</strong> ${new Date().toLocaleDateString()}</div>
    </div>
  </div>
  <div class="rule"></div>

  <table>
    <thead>
      <tr>
        <th>Item</th><th class="right">Unit</th><th class="right">Qty</th><th class="right">Amount</th>
      </tr>
    </thead>
    <tbody>
      ${itemsRows || `<tr><td colspan="4" class="muted">No line items.</td></tr>`}
    </tbody>
  </table>

  <table class="totals">
    <tr><td>Subtotal</td><td class="right">${fmt(q?.subtotal || 0, q?.currency)}</td></tr>
    <tr><td>Shipping</td><td class="right">${fmt(q?.shipping || 0, q?.currency)}</td></tr>
    <tr><td>Tax</td><td class="right">${fmt(q?.tax || 0, q?.currency)}</td></tr>
    <tr><td><strong>Total</strong></td><td class="right"><strong>${fmt(q?.total || 0, q?.currency)}</strong></td></tr>
  </table>

  ${notes ? `<div style="margin-top:12px"><strong>Notes:</strong><ul>${notes}</ul></div>` : ""}
  <div class="muted" style="margin-top:24px">Generated by Brand M3dia Kiosk Ordering System.</div>
  <script>window.print()</script>
</body>
</html>`;

  const w = window.open("", "_blank", "width=1080,height=800");
  if (!w) return;
  w.document.write(html);
  w.document.close();
  w.focus();

  function esc(x) {
    return String(x ?? "").replace(/[&<>"']/g, (m) => ({ "&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;" }[m]));
  }
  function fmt(n, cur = "USD") {
    try { return new Intl.NumberFormat(undefined, { style:"currency", currency:cur }).format(Number(n||0)); }
    catch { return `$${Number(n||0).toFixed(2)}`; }
  }
}
